
package compilador.View;

import compilador.Controle.ControleEditor;
import compilador.Controle.ModeloTabelaToken;
import compilador.Estruturas.Token;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.Stack;
import javax.swing.UIManager;


public class Editor extends javax.swing.JFrame {

    ModeloTabelaToken modelotabela = new ModeloTabelaToken();
    ActionListener listener = new ControleEditor(this);

    public Editor() {
        initComponents();
        tabela.setModel(modelotabela);
        this.setLocationRelativeTo(null);

    }

    public void addTabela(Stack<Token> pilha) {
        System.out.println("Tamanho nova pilha: " + pilha.size());
        limpaTabela();
        for (int i = 0; i < pilha.size(); i++) {
            modelotabela.addRow(pilha.elementAt(i));
        }
    }

    public void limpaTabela() {
        int tam = modelotabela.getRowCount();
        System.out.println("Tamanho velha pilha: " + tam);
        for (int i = 0; i < tam; i++) {
            modelotabela.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_editor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuSalvar = new javax.swing.JMenuItem();
        menuSalvarComo = new javax.swing.JMenuItem();
        menuFechar = new javax.swing.JMenuItem();
        Compilar = new javax.swing.JMenu();
        menuCompilar = new javax.swing.JMenuItem();

        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area_editor.setColumns(20);
        area_editor.setLineWrap(true);
        area_editor.setRows(5);
        area_editor.setText("(*TESTE - Exemplo Válido*)\nProgram TESTE123;\n\tLabel\n\t\tlabel_a, label_b;\n\t\n\tConst\n\t\ta = 100;\n\t\tb = 200;\n\tVar \n\t\t X, Y, Z : Integer;\n\t\tarray_a : Array[0..20] Of Integer;\n\t\tarray_b, array_c, array_d : Array[0..1000] Of Integer;\n\t\n\t(*Declaração de procedure, inicia novo bloco*)\n\tProcedure p_teste(idd : Integer);\n\t\tLabel\n\t\t\tlabel_a, label_b;\n\t\t\t\n\t\tConst\n\t\t\ta = 100;\n\t\t\tb = 200;\n\n\t\tVar \n\t\t\tX, Y, Z : Integer;\n\t\t\tarray_a : Array[0..20] Of Integer;\n\t\t\tarray_b : Array[0..1000] Of Integer;\n\tBegin\n\t\tX := a * b;\n\n\tEnd;\n\n(*\t\n\t- Início do bloco principal\n*)\n\nBegin\n\tX := 150;\n\tBegin\n\t\tX := 20;\n\tEnd;\n\t\n\t(*Chama a procedure*)\n\tCall p_teste( 100 );\n\t\n\t(*Testa as possibilidades do IF*)\n\tIf (10 > 15) Then\n\t\tBegin\n\t\tEnd\n\tElse\n\t\tBegin\n\t\tEnd;\n\n\t(*Testa as possibilidades do WHILE*)\n\tWhile(X <> 0)Do\n\tBegin\n\tEnd; \n\n\t(*Testa as possibilidades do REPEAT*)\n\tRepeat\n\tBegin \n\tEnd\n\tUntil X > 10;\n\n\t(*Testa as possibilidades do WRITELN*)\n\tWriteln(X,Z,Y);\n\n\t(*Testa as possibilidades do FOR*)\n\tFor X := Y > 2 To 10 - 2 Do\n\tBegin\n\tEnd;\n\n\t(*Testa as possibilidades do CASE*)\n\tCase a + 2 Of\n\t\t10 : Begin End;\n\t\t20 : Begin End;\n\t\t30 : Begin End\n\tEnd;\nEnd.");
        jScrollPane1.setViewportView(area_editor);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Palavra"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        jMenu1.setText("Arquivo");

        menuAbrir.addActionListener(listener);
        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbrir);

        menuSalvar.addActionListener(listener);
        menuSalvar.setText("Salvar");
        jMenu1.add(menuSalvar);

        menuSalvarComo.addActionListener(listener);
        menuSalvarComo.setText("Salvar Como");
        menuSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalvarComoActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalvarComo);

        menuFechar.addActionListener(listener);
        menuFechar.setText("Fechar");
        jMenu1.add(menuFechar);

        jMenuBar1.add(jMenu1);

        Compilar.setText("Compilar");

        menuCompilar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menuCompilar.addActionListener(listener);
        menuCompilar.setText("Compila");
        menuCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompilarActionPerformed(evt);
            }
        });
        Compilar.add(menuCompilar);

        jMenuBar1.add(Compilar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed

    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompilarActionPerformed
        //Compilador.rodarLexico(getTexto());
    }//GEN-LAST:event_menuCompilarActionPerformed

    private void menuSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalvarComoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalvarComoActionPerformed

    public static void gravar(String path, String texto) throws FileNotFoundException, IOException {
        FileOutputStream arq = null;
        PrintStream ps = null;

        try {
            File arquivo = new File(path);
            arq = new FileOutputStream(arquivo);

            try {

            } catch (Exception e) {
            }
        } catch (Exception e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    /**
     *
     */
    @Override
    public void setResizable(boolean bln) {
        super.setResizable(bln); //To change body of generated methods, choose Tools | Templates.
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            /* for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Editor().setVisible(true);
        });
    }

    public String getTexto() {
        return area_editor.getText();
    }

    public void setTexto(String texto) {
        area_editor.setText(texto);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Compilar;
    private javax.swing.JTextArea area_editor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuCompilar;
    private javax.swing.JMenuItem menuFechar;
    private javax.swing.JMenuItem menuSalvar;
    private javax.swing.JMenuItem menuSalvarComo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
